import pyautogui
import pyperclip
import time

pyautogui.click(1000,500)
time.sleep(2.10)

i = 1
while i <= 2:
    pyautogui.press("z")
    time.sleep(0.313)
    pyautogui.press("down")
    time.sleep(0.245)
    pyautogui.press("z")
    time.sleep(0.218)
    pyautogui.press("z")
    time.sleep(0.271)
    pyautogui.press("z")
    time.sleep(0.2454)
    pyautogui.press("z")
    time.sleep(0.298)
    pyautogui.press("z")
    time.sleep(0.2812)
    pyautogui.press("z")
    time.sleep(0.313)
    pyautogui.press("z")
    time.sleep(0.248)
    pyautogui.press("z")
    time.sleep(0.2747)
    pyautogui.press("z")
    time.sleep(0.212)
    pyautogui.press("z")
    time.sleep(0.208)
    pyautogui.press("z")
    time.sleep(0.259)
    pyautogui.press("z")
    time.sleep(0.2946)
    pyautogui.press("z")
    time.sleep(0.289)
    pyautogui.press("z")
    time.sleep(0.2244)
    pyautogui.press("z")
    time.sleep(0.2187)
    pyautogui.press("z")
    time.sleep(1.00)
    pyautogui.press("x")
    time.sleep(0.327)
    pyautogui.press("down")
    time.sleep(0.3958)
    pyautogui.press("z")
    time.sleep(0.3686)
    pyautogui.press("z")
    time.sleep(0.2013)
    pyautogui.press("z")
    time.sleep(0.3572)
    pyautogui.press("z")
    time.sleep(0.2142)
    pyautogui.press("z")
    time.sleep(0.2537)
    pyautogui.press("z")
    time.sleep(0.2196)
    pyautogui.press("z")
    time.sleep(0.3864)
    pyautogui.press("z")
    time.sleep(0.3992)
    pyautogui.press("z")
    time.sleep(0.2422)
    pyautogui.press("z")
    time.sleep(0.2441)
    pyautogui.press("z")
    time.sleep(0.2544)
    pyautogui.press("z")
    time.sleep(0.3971)
    pyautogui.press("z")
    time.sleep(0.2745)
    pyautogui.press("z")
    time.sleep(0.392)
    pyautogui.press("z")
    time.sleep(0.263)
    pyautogui.press("z")
    time.sleep(0.2436)
    pyautogui.press("z")
    time.sleep(1.137)
    pyautogui.press("up")
    time.sleep(0.332)
    i = i + 1
